version = 1
disable_existing_loggers = true

[handlers.default]
class = "logging.StreamHandler"
formatter = "precise"
level = "INFO"
stream = "ext://sys.stdout"

[handlers.short]
class = "logging.StreamHandler"
formatter = "short"
level = "DEBUG"
stream = "ext://sys.stdout"

[formatters.precise]
format = "%(asctime)s loglevel=%(levelname)-6s logger=%(name)s %(funcName)s() L%(lineno)-4d %(message)s call_trace=%(pathname)s L%(lineno)-4d"
datefmt = "%Y-%m-%d %H:%M:%S"

[formatters.short]
format = "%(asctime)s.%(msecs)3d %(levelname)s:%(name)s: %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[loggers.dciosmartdata]
handlers = ["short"]
level = "INFO"
propogate = true
